# Generated by Django 2.0.5 on 2018-07-05 07:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('commented_on', models.DateTimeField(default=datetime.datetime(2018, 7, 5, 12, 40, 16, 661344))),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('question_title', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 7, 5, 12, 40, 16, 660343))),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('no_of_comments', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='comm_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Questions'),
        ),
    ]
