# Generated by Django 2.0.5 on 2018-07-05 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 12, 41, 18, 634798)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 12, 41, 18, 632798)),
        ),
    ]
